### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by mayagokhale** [anikau31/systemc-clang#107]
It would be good to have a standard error/warning reporting mechanism for the plugin. Maybe there is already something in place and I haven't found it. I'm looking for the best way to report to the user that "break" statements aren't handled and will be ignored.

**Comment by rseac** [comment]
@mayagokhale You're correct.  We probably do need a good way to do this and be consistent in the main tool too. I wonder if this could guide us: [https://llvm.org/docs/ProgrammersManual.html#error-handling ](https://llvm.org/docs/ProgrammersManual.html#error-handling )

**Comment by rseac** [comment]
I think a good way to do this would be to use `LLVM_DEBUG()` macro. It allows one to turn on and off debug output given certain types. I've added the code in xlat, and systemc-clang to allow for this. Essentially, with the use of `LLVM_DEBUG()`, one can now pass the `--debug` flag to the tool to print all the debug outputs. Alternatively, one could selectively output the debug output by using the `--debug-only` flag.  The way to set this would be to set `DEBUG_TYPE` in the respective header. 

Currently, examples that use this include the `SensitivityMatcher` and `InstanceMatcher` in `src/matchers/`.

**Comment by rseac** [comment]
We should create a macro that wraps `LLVM_DEBUG()` within it. This makes it easy to use the corresponding code within our debug.
```c++
#undef DEBUG_TYPE
#define DEBUG_TYPE some_name
```

**Comment by rseac** [comment]
There seems to be no need to do this. LLVM Debug allows for this via the ``DEBUG_WITH_TYPE()`` macro.

**Comment by rseac** [comment]
I'm assuming that we are good with this approach.

**Comment by mayagokhale** [comment]
Yes, that will work well.
