### ISSUE TITLE
Submodules and their port bindings

### ISSUE THREAD

**Issue by mayagokhale** [anikau31/systemc-clang#108]
The xlat plugin is not handling submodule instantiation. Submodules appear in the OtherVars list in a module and are being processed as regular variables, not as submodules to be instantiated. Processing the vector of submodules needs to be done, and the plugin must not include them as variables with flattened declarations. @mayagokhale needs to add this code.

**Comment by rseac** [comment]
@mayagokhale One way to access the sub-modules is to access the following from a `ModuleDecl`: https://github.com/anikau31/systemc-clang/blob/master/src/model/ModuleDecl.h#L125
https://github.com/anikau31/systemc-clang/blob/master/src/model/ModuleDecl.h#L174 

This would provide access to the `ModuleDecl` for the corresponding sub-module instance.

**Comment by mayagokhale** [comment]
Submodule processing has been implemented.
