### ISSUE TITLE
clang compiler error on reference to llvm::setCurrentDebugType

### ISSUE THREAD

**Issue by mayagokhale** [anikau31/systemc-clang#131]
clang 11.0 on mac give an error message "error: expected unqualified-id" on reference llvm::setCurrentDebugType in PluginAction.h and Xlat.h. Removing the "llvm::" results in normal compilation on clang, and generates error message on g++ 7.5 on linux. 
Current workaround is 
#ifdef  __clang__
      setCurrentDebugType(debug_only.c_str());
#else
      llvm::setCurrentDebugType(debug_only.c_str());
#endif

**Comment by mayagokhale** [comment]
I tested on gcc7.3 not 7.5.

**Comment by rseac** [comment]
I'm assuming the fix for the PR fixes this issue?

**Comment by mayagokhale** [comment]
Yes, systemc-clang compiles without error using the xlat plugin on my mac.
