### ISSUE TITLE
Arrays as sensitivity list arguments

### ISSUE THREAD

**Issue by rseac** [anikau31/systemc-clang#169]
Sensitivity list generation with arguments as arrays are not captured.

```
    sensitive << x[stages-1] << y[stages-1] << z[stages-1] << w[stages-1]; 
```

**Comment by rseac** [comment]
@mayagokhale Each of the arguments to the `operator<<` call for the sensitivity list is an `ArraySubscriptExpr`. I can certainly provide a pointer to each one of those. Would that be sufficient?

**Comment by mayagokhale** [comment]
Pointer to the subscript expression would be fine. I can apply HDLBody to it.

**Comment by rseac** [comment]
9e1ae8f includes support for recognizing arrays as arguments for sensitivity lists.

**Comment by mayagokhale** [comment]
Since the for loop wasn't being captured, I wasn't able to use that information, similarly to the port bindings in for loops. Now the hcode analysis pass is processing all port bindings and sensitivity lists.
