### ISSUE TITLE
Multiple instances/declarations when matching templated module using ASTMatcher

### ISSUE THREAD

**Issue by zhuanhao-wu** [anikau31/systemc-clang#28]
# Description

When matching the templated modules, such as the sreg module in the example, it might create multiple module declarations for multiple instantiations with different type parameters.

# Reproducing the bug 

Running the `sreg-test` should reveal the problem. 

# Expected Behavior
The number of instances/declarations should match the number of instantiations in the code.

# Actual Behavior
If we look at the number of instances/declarations generated for the three instances with different type parameters, we can observe there are 9 in total.

**Comment by zhuanhao-wu** [comment]
b69e745
Added test for the issue.

**Comment by rseac** [comment]
@zhuanhao-wu I've pushed in a new branch called `integrate-matchers` at c493575f11b5b98377fc87162cdcdd8fe4e33c2e.  Can you ensure that the sreg test, which is passing for templated modules, is indeed correct.

**Comment by rseac** [comment]
Fixed in #35.
