### ISSUE TITLE
non-simple type argument not included in port, signal type info

### ISSUE THREAD

**Issue by mayagokhale** [anikau31/systemc-clang#30]
For sc_in etc. of simple type e.g. sc_in<Bool>, the type info associated with the declaration has two parameters, TemplateSpecializationType and BuiltinType:
 
```bash
number of type args is 2
TemplateSpecializationType 0x3d985a0 'sc_in<_Bool>' sugar sc_in
|-TemplateArgument type '_Bool'
`-RecordType 0x2fc96f0 'class sc_core::sc_in<_Bool>'
  `-ClassTemplateSpecialization 0x33f4e28 'sc_in'
BuiltinType 0x1ef14d0 '_Bool'
```
 
However for complex types, the second parameter is not included:
```bash
number of type args is 1
TemplateSpecializationType 0x3da0ed0 'sc_stream<find_emax::expo_t>' dependent sc_stream
`-TemplateArgument type 'find_emax::expo_t':'typename FP::expo_t'
```

Should complex types also resolve to a leaf class? The expo_t is defined as 
typedef sc_uint<E> expo_t;
and E is a constant via a define:
#define E 11

**Comment by rseac** [comment]
Fixed in #35
