### ISSUE TITLE
Hcode generator hangs on test_fcall_base.cpp

### ISSUE THREAD

**Issue by zhuanhao-wu** [anikau31/systemc-clang#325]
# Description

When running `systemc-clang` binary on [test_fcall_base.cpp](https://github.com/intel/systemc-compiler/blob/main/tests/method/test_fcall_base.cpp), the binary does not stop and does not produce _hdl.txt file.

# Reproducing the bug 

`bash /systemc-clang/scripts/run.sh /systemc-compiler/tests/method/test_fcall_base.cpp`

**Comment by mayagokhale** [comment]
I have fixed the bug and done a push. CI will still fail as the z3test parsing problem isn't yet fixed.

However, this example uncovered another issue related to explicitly specified inherited method invocation, which will be posted.
