### ISSUE TITLE
`xnor_reduce` should be a builtin function

### ISSUE THREAD

**Issue by zhuanhao-wu** [anikau31/systemc-clang#356]
https://github.com/intel/systemc-compiler/blob/main/tests/method/test_unary_sc.cpp#L94

```c++
bool l2 = xnor_reduce(x2);
```

Currently we are generating `hFunction`
```
hFunction sc_dt__xnor_reduce_func_0 [
```

**Comment by mayagokhale** [comment]
should be fixed in latest commit.

**Comment by mayagokhale** [comment]
fixed
