### ISSUE TITLE
test_level2.cpp fails

### ISSUE THREAD

**Issue by zhuanhao-wu** [anikau31/systemc-clang#368]
The systemc-clang binary crashes, it does not seem to be a syntax error.
The design is a mix of thread and processes.

https://github.com/intel/systemc-compiler/blob/main/tests/method/test_level2.cpp

The last couple lines of log:

```
systemc-clang: /opt/clang-13.0.0/include/llvm/ADT/SmallVector.h:281: const T& llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::operator[](llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::size_type) const [with T = std::pair<const systemc_clang::SplitCFGBlock*, systemc_clang::SupplementaryInfo>; <template-parameter-1-2> = void; llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::const_reference = const std::pair<const systemc_clang::SplitCFGBlock*, systemc_clang::SupplementaryInfo>&; llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::size_type = long unsigned int]: Assertion `idx < size()' failed.
Aborted (core dumped)
```

**Comment by rseac** [comment]
Started digging into this.  It appears to be within the `break_in_while_for` thread process.

**Comment by rseac** [comment]
It appears that 4638531fbc9295a61a1b02c2b2d861e11fd5a9de fixes the crash.  Essentially, correctly identifying IF blocks in the SplitCFG.

**Comment by rseac** [comment]
This should be fixed in scratchllnl.

**Comment by rseac** [comment]
Confirmed that it does not crash on current scratchllnl. Closing.
