### ISSUE TITLE
Extract LHS and RHS Expressions in For Loop Body

### ISSUE THREAD

**Issue by therealgymmy** [anikau31/systemc-clang#4]
Given a for loop body.

We should separate out all the LHS and RHS variables of an assignment operation.
In case of other binary operation, both LHS and RHS are only `read` variables.

**Comment by BeyondSora** [comment]
Tracking all local LHS and RHS array variables as of commit 3dd96976abb13a9bbad8e3fd376410dd62d3fa32.

Next step:
Track class-wide arrays.
