### ISSUE TITLE
segv in FindTemplateTypes (master branch)

### ISSUE THREAD

**Issue by mayagokhale** [anikau31/systemc-clang#40]
systemc-clang gives segmentation violation in scpar::FindTemplateTypes::VisitType (FindTemplateTypes.cpp:98) on test program examples/filter/main_sc.cpp when called from the xlat plugin file XlatEntryMethod.cpp:159 which is enumerating a template type retrieved from a VarDecl's getType() method.

Stack trace:

ProcessVarDecl type name is sc_bv<8>

Program received signal SIGSEGV, Segmentation fault.
0x00000000014148e6 in (anonymous namespace)::TypePrinter::printBefore(clang::QualType, llvm::raw_ostream&) ()
Missing separate debuginfos, use: debuginfo-install glibc-2.17-292.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64 ncurses-libs-5.9-14.20130511.el7_4.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) where
#0  0x00000000014148e6 in (anonymous namespace)::TypePrinter::printBefore(clang::QualType, llvm::raw_ostream&) ()
#1  0x00000000014138b1 in (anonymous namespace)::TypePrinter::printBefore(clang::Type const*, clang::Qualifiers, llvm::raw_ostream&) ()
#2  0x0000000001414aa5 in clang::QualType::getAsStringInternal(clang::Type const*, clang::Qualifiers, std::string&, clang::PrintingPolicy const&) ()
#3  0x0000000001414cbf in clang::QualType::getAsString(clang::Type const*, clang::Qualifiers, clang::PrintingPolicy const&) ()
#4  0x0000000001414db4 in clang::QualType::getAsString() const ()
#5  0x0000000000691b64 in scpar::FindTemplateTypes::VisitType (this=0x3b379a0, 
    type=0x3e12800)
    at /home/gokhale2/sumac-home/src/systemc-clang-top/systemc-clang/src/FindTemplateTypes.cpp:98
#6  0x000000000069cda5 in WalkUpFromType (T=0x3e12800, this=<optimized out>)
    at /home/gokhale2/local/llvm7/include/clang/AST/RecursiveASTVisitor.h:437
#7  WalkUpFromTemplateSpecializationType (T=0x3e12800, this=<optimized out>)
    at /home/gokhale2/local/llvm7/include/clang/AST/TypeNodes.def:100
#8  TraverseTemplateSpecializationType (T=0x3e12800, this=0x3b379a0)
    at /home/gokhale2/local/llvm7/include/clang/AST/RecursiveASTVisitor.h:1062
#9  clang::RecursiveASTVisitor<scpar::FindTemplateTypes>::TraverseType (
    this=this@entry=0x3b379a0, T=..., T@entry=...)
    at /home/gokhale2/local/llvm7/include/clang/AST/TypeNodes.def:100
#10 0x000000000069d170 in scpar::FindTemplateTypes::Enumerate (
---Type <return> to continue, or q <return> to quit---
    this=this@entry=0x3b379a0, type=type@entry=0x3e12800)
    at /home/gokhale2/sumac-home/src/systemc-clang-top/systemc-clang/src/FindTemplateTypes.cpp:70
#11 0x00000000007c715a in XlatMethod::ProcessVarDecl (
    this=this@entry=0x7fffffffc1b0, vardecl=vardecl@entry=0x3e128a8, 
    h_vardecl=@0x7fffffffbee0: 0x448f980)
    at /home/gokhale2/sumac-home/src/systemc-clang-top/systemc-clang/plugins/xlat/XlatEntryMethod.cpp:159
#12 0x00000000007c74d2 in XlatMethod::TraverseDeclStmt (
    this=this@entry=0x7fffffffc1b0, declstmt=declstmt@entry=0x3e12d18)
    at /home/gokhale2/sumac-home/src/systemc-clang-top/systemc-clang/plugins/xlat/XlatEntryMethod.cpp:144
#13 0x00000000007b7a13 in XlatMethod::TraverseStmt (
    this=this@entry=0x7fffffffc1b0, stmt=0x3e12d18)
    at /home/gokhale2/sumac-home/src/systemc-clang-top/systemc-clang/plugins/xlat/XlatEntryMethod.cpp:55
#14 0x00000000007c6f41 in XlatMethod::TraverseCompoundStmt (
    this=this@entry=0x7fffffffc1b0, cstmt=cstmt@entry=0x3e1a6a0)
    at /home/gokhale2/sumac-home/src/systemc-clang-top/systemc-clang/plugins/xlat/XlatEntryMethod.cpp:123
#15 0x00000000007b79fb in XlatMethod::TraverseStmt (
    this=this@entry=0x7fffffffc1b0, stmt=0x3e1a6a0)
    at /home/gokhale2/sumac-home/src/systemc-clang-top/systemc-clang/plugins/xla---Type <return> to continue, or q <return> to quit---q

**Comment by rseac** [comment]
@mayagokhale This should be okay now ...
