### ISSUE TITLE
Which class should I pay attention to if I want to get the symbol table

### ISSUE THREAD

**Issue by Elwin-zhao** [anikau31/systemc-clang#405]
# Description

# Reproducing the bug 

## Versions 
- systemc-clang: [i.e. 0.1]
- CXX compiler: [i.e. clang-7.0.0]
- CXX flags: [i.e. llvm-config --cxxflags]
- SystemC: [i.e. 2.3.3]
- Operating System: [i.e. Ubuntu 18.04]

## Minimal Working Example (MWE)
Provide a minimal working example that illustrates the bug.
```c++
int main() { 
  // Code here.
  return 0;
}
```

## Steps to Reproduce Bug
1. Do this
2. Do that
3. Compile that

### Actual behaviour
Explain the actual behviour observed.

**Comment by Elwin-zhao** [comment]
I have taken a look at SystemCConsumer and getContext method. And which class and method should I take a look at if I want to get the symbol table? @mayagokhale @rseac

**Comment by rseac** [comment]
@Elwin-zhao  I'm not entirely sure what you're looking for from within systemc-clang.  Could you give me a concrete example of what you are looking for when asking about the symbol table?

**Comment by Elwin-zhao** [comment]
I want to use symbol table to

> @Elwin-zhao I'm not entirely sure what you're looking for from within systemc-clang. Could you give me a concrete example of what you are looking for when asking about the symbol table?

I want to get the value of the variable at every moment during runtime, because it involves multi-threaded reading and writing of variables. By extracting the information of the abstract syntax tree and putting it into the symbol table, the value of the runtime variable at each moment can be obtained when the systemc simulation program is running, which can be used to detect data conflicts. @rseac

**Comment by rseac** [comment]
Clang provides static information. As far as I know, it does not provide runtime information.  You can access the AST.  This is what I had mentioned earlier where you can get Clang's AST from the ASTContext. https://clang.llvm.org/docs/IntroductionToTheClangAST.html 

Hope this helps.
