### ISSUE TITLE
parsing without main

### ISSUE THREAD

**Issue by Hassan05** [anikau31/systemc-clang#6]
When I try to parse the following file which does not contain main function
[my_dut.h.txt](https://github.com/anikau31/systemc-clang/files/335080/my_dut.h.txt)

I get 

>  Could not find SCMainsystemc-clang: /home/hassan/systemc-clang/src/FindSCMain.cpp:39: clang::FunctionDecl\* scpar::FindSCMain::getSCMainFunctionDecl(): Assertion `!(_scmainFunctionDecl == __null)' failed.
> Aborted (core dumped)

Is it possible to parse a file without main?

**Comment by rseac** [comment]
Several separate issues need to be resolved in order to specify the top-level module declaration. 
1. The CommonOptionsParser needs to be used to extract the top-level module.
2. This should be used as the entry when the traversal begins; instead of starting by finding the main().

**Comment by rseac** [comment]
Fixed in #35.
