### ISSUE TITLE
Parse array of ports for their netlist

### ISSUE THREAD

**Issue by rseac** [anikau31/systemc-clang#98]
# Description
Parse array of ports appropriately, and build a netlist for it. 
The example that should pass is the `portarray-example.cpp`

**Comment by rseac** [comment]
The parsing of array of ports and signals is being done so that its array size is being found. However, what the ports are bound to is not parsed yet.

**Comment by rseac** [comment]
Fixed. 203ab4c

**Comment by mayagokhale** [comment]
What value is returned for array size if is_array is false? In the code in PortDecl.cpp, there didn't seem to be an initial value set for it. is_array is initialized to false but the size isn't. It would be convenient if the size were zero if it isn't an array.

**Comment by rseac** [comment]
I've initialized it to 0 now in PortDecl.
